import Foundation

private let englishText: [String: String] = [
    "PPTP 프락시": "PPTP Proxy",
    "프로필·연결": "Profiles & Connection",
    "프락시 설정": "Proxy Settings",
    "연결 중에 앱을 종료하시겠습니까?": "Quit while connected?",
    "앱을 종료하면 PPTP 연결도 종료될 수 있습니다.": "Quitting may also end the PPTP connection.",
    "연결 해제하고 종료": "Disconnect and Quit",
    "취소": "Cancel",
    "백엔드의 연결 해제 응답이 올바르지 않습니다.": "The backend returned an invalid disconnect response.",
    "연결 해제에 실패했습니다": "Could Not Disconnect",
    "프로필을 선택하거나 새로 등록하세요.": "Select a profile or create a new one.",
    "아직 연결 로그가 없습니다.": "No connection log yet.",
    "설정을 바꾸면 적용을 누르세요.": "Click Apply after changing settings.",
    "Safari·프락시 클라이언트용 VPN 연결": "VPN access for Safari and proxy clients",
    "화면": "Page",
    "연결 해제 중": "Disconnecting",
    "PPP/MPPE 연결됨": "PPP/MPPE connected",
    "연결 중": "Connecting",
    "연결 안 됨": "Disconnected",
    "연결 해제 중…": "Disconnecting…",
    "연결 해제": "Disconnect",
    "프로필": "Profile",
    "새 프로필": "New profile",
    "이름": "Name",
    "프로필 이름": "Profile name",
    "PPTP 서버": "PPTP server",
    "서버 주소": "Server address",
    "VPN 아이디": "VPN user name",
    "아이디": "User name",
    "VPN 암호": "VPN password",
    "키체인에 저장됨 · 변경하려면 입력": "Saved in Keychain · enter to change",
    "VPN 계정 암호": "VPN account password",
    "신규 등록": "New profile",
    "저장": "Save",
    "삭제": "Delete",
    "암호는 키체인에 저장됨": "Password saved in Keychain",
    "연결": "Connect",
    "남은 연결 정리": "Clean Up Remaining Connection",
    "로그 접기": "Hide Log",
    "로그 보기": "Show Log",
    "프로필을 저장하면 포트포워딩 규칙도 함께 보관됩니다.": "Save a profile to keep its port forwarding rules.",
    "HTTP 프락시": "HTTP proxy",
    "SOCKS5 프락시": "SOCKS5 proxy",
    "수동 포트포워딩": "Manual port forwarding",
    "한 줄에 로컬포트:대상호스트:대상포트 (예: 15432:10.0.0.5:5432)": "One rule per line: local-port:destination-host:destination-port (for example, 15432:10.0.0.5:5432)",
    "적용": "Apply",
    "Safari는 macOS 네트워크 설정의 웹·보안 웹 프락시에 HTTP 주소를 입력하세요. 수동 포트는 이 Mac의 127.0.0.1에서만 열립니다.": "For Safari, enter the HTTP address under macOS Network settings for Web and Secure Web Proxy. Manual ports listen only on this Mac's 127.0.0.1.",
    "실패: 포트 또는 포워딩 형식을 확인하세요.": "Failed: Check the port or forwarding rule format.",
    "프락시 포트를 저장했습니다. 포워딩 규칙은 프로필 저장 후 유지됩니다.": "Proxy ports saved. Save a profile to keep forwarding rules.",
    "저장했습니다. 다음 연결부터 적용됩니다.": "Saved. Changes will apply to the next connection.",
    "실패: 연결 정보를 찾을 수 없습니다.": "Failed: Connection information was not found.",
    "현재 연결에 설정을 적용하는 중입니다.": "Applying settings to the current connection.",
    "현재 연결에 적용했습니다. 새 연결부터 변경된 설정을 사용합니다.": "Applied to the current connection. New connections will use the changed settings.",
    "실패: 설정 형식 또는 포트 충돌을 확인하세요.": "Failed: Check the setting format or for a port conflict.",
    "실패: 서버와 아이디를 확인하세요.": "Failed: Check the server and user name.",
    "실패: VPN 계정 암호를 입력하세요.": "Failed: Enter the VPN account password.",
    "프로필을 저장했습니다.": "Profile saved.",
    "프로필과 키체인 암호를 삭제했습니다.": "Profile and Keychain password deleted.",
    "실패: 앱 번들에 실행 파일이 없습니다.": "Failed: An executable is missing from the app bundle.",
    "실패: 프락시 설정 화면의 포트와 포워딩 규칙을 확인하세요.": "Failed: Check the ports and forwarding rules under Proxy Settings.",
    "실패: 저장된 암호가 없습니다.": "Failed: No saved password was found.",
    "연결 로그를 기다리는 중입니다.": "Waiting for the connection log.",
    "관리자 권한을 확인한 뒤 PPTP 연결을 시작합니다.": "Approve administrator access to start the PPTP connection.",
    "PPP/MPPE 협상 중입니다.": "Negotiating PPP/MPPE.",
    "연결이 이미 종료됐습니다.": "The connection has already ended.",
    "연결 해제를 요청하는 중입니다.": "Requesting disconnection.",
    "연결 해제 요청을 보냈습니다. 종료를 기다리는 중입니다.": "Disconnect requested. Waiting for the backend to exit.",
    "관리자 권한 확인 창을 먼저 취소하거나 완료한 뒤 연결을 해제하세요.": "Complete or cancel the administrator prompt before disconnecting.",
    "연결 프로세스가 이미 종료돼 화면 상태를 정리했습니다.": "The connection process has ended; the displayed state was cleared.",
    "실패: 앱 실행 파일과 프락시 포트를 확인하세요.": "Failed: Check the app executable and proxy ports.",
    "남은 연결을 확인하는 중입니다. 관리자 권한을 요청할 수 있습니다.": "Checking for a remaining connection. Administrator access may be requested.",
    "남은 PPTP 프락시 프로세스에 종료를 요청했습니다. 잠시 뒤 다시 연결하세요.": "Asked the remaining PPTP proxy process to exit. Try connecting again shortly.",
    "현재 프락시 포트에서 이 앱의 남은 연결을 찾지 못했습니다.": "No remaining process from this app was found on the proxy ports.",
    "PPP/MPPE 연결됨. 프락시에서 원격 접속을 시도할 수 있습니다.": "PPP/MPPE connected. You can now access remote services through the proxy.",
    "연결을 해제했습니다.": "Disconnected.",
    "실패: PPTP 데이터 채널이 열리지 않았습니다. GRE 경로와 로그를 확인하세요.": "Failed: The PPTP data channel did not open. Check the GRE path and log.",
    "실패: PPP 협상 또는 인증이 종료됐습니다. 로그를 확인하세요.": "Failed: PPP negotiation or authentication ended. Check the log.",
    "연결이 종료됐습니다.": "Connection ended.",
    "연결 프로세스가 종료돼 화면 상태를 정리했습니다.": "The connection process ended; the displayed state was cleared.",
    "실패: 연결 상태를 확인할 수 없습니다. 다시 시도하거나 로그를 확인하세요.": "Failed: Cannot check connection status. Try again or check the log.",
    "실패: PPP 연결이 끊어졌습니다. 로그를 확인하세요.": "Failed: The PPP connection dropped. Check the log.",
    "제어 소켓 경로가 너무 깁니다.": "The control socket path is too long.",
    "VPN 암호 전달 대기 시간이 초과됐습니다.": "Timed out while delivering the VPN password.",
    "PPP 연결 종료/실패": "PPP connection ended/failed",
    "실패": "Failed"
]

// These fragments cover messages with interpolated ports, profile names, system
// errors, and the backend's log lines. Keep the backend's original log text for
// connection-state detection; translate only the text presented to the user.
private let englishFragments: [(String, String)] = [
    ("앱을 종료하지 않았습니다. 다시 시도하거나 로그를 확인하세요. ", "The app remains open. Try again or check the log. "),
    ("현재 프로필: ", "Current profile: "),
    ("보냄 ", "Sent "),
    ("받음 ", "Received "),
    ("키체인 확인 실패: ", "Keychain check failed: "),
    ("실패: 로컬 포트 ", "Failed: Local port "),
    ("를 열 수 없습니다.", " could not be opened."),
    ("실패: 현재 연결에 적용하지 못했습니다: ", "Failed: Could not apply settings to the current connection: "),
    ("실패: 키체인 저장 오류: ", "Failed: Keychain save error: "),
    ("실패: 키체인 삭제 오류: ", "Failed: Keychain delete error: "),
    ("실패: 키체인 암호 읽기 오류: ", "Failed: Could not read the Keychain password: "),
    ("실패: 연결 시작 오류: ", "Failed: Could not start the connection: "),
    ("실패: 연결 준비 오류: ", "Failed: Could not prepare the connection: "),
    ("실패: 연결 해제 응답이 올바르지 않습니다: ", "Failed: Invalid disconnect response: "),
    ("실패: 연결 해제 요청을 보낼 수 없습니다: ", "Failed: Could not send the disconnect request: "),
    ("실패: 남은 연결 정리 오류: ", "Failed: Could not clean up the remaining connection: "),
    ("로그 읽기 실패: ", "Failed to read log: "),
    ("원격 TCP 오류 ", "Remote TCP error "),
    ("원격 연결 ", "Remote connection "),
    ("VPN DNS 실패: ", "VPN DNS failure: "),
    ("PPP 연결 전 요청 거부: ", "Request rejected before PPP connection: "),
    ("accept 오류: ", "Accept error: "),
    ("PPTP 전송 실패: ", "PPTP send failure: "),
    ("PPP/MPPE 연결됨: ", "PPP/MPPE connected: "),
    ("PPP 주소 협상 완료, MPPE 협상 미완료", "PPP address negotiated; MPPE negotiation incomplete"),
    ("PPP 연결 종료/실패: ", "PPP connection ended/failed: "),
    ("프락시 설정 적용: ", "Proxy settings applied: "),
    ("포워딩 ", "forwards "),
    ("%zu개", "%zu"),
    ("연결 해제 요청 수신", "Disconnect request received"),
    ("제어 소켓 생성 실패: ", "Could not create control socket: "),
    ("VPN 암호 입력 실패 또는 시간 초과", "VPN password input failed or timed out"),
    ("VPN 암호가 비어 있습니다", "VPN password is empty"),
    ("사용법: ", "Usage: "),
    ("VPN 암호는 표준입력 또는 지정된 FIFO의 첫 줄로 받습니다. GRE raw socket을 여는 실행 권한이 필요합니다.", "The VPN password is read from standard input or the first line of the selected FIFO. Opening a GRE raw socket requires administrator privileges."),
    ("로컬 포트 ", "Local port "),
    (" 사용 실패: ", " unavailable: "),
    ("PPTP 실행 실패: ", "Could not launch PPTP: "),
    ("PPP 초기화 실패", "PPP initialization failed"),
    ("PPP 시작 실패", "Could not start PPP"),
    ("PPTP 서버 ", "PPTP server "),
    (" 연결 중", " connecting"),
    (" 대기", " listening"),
    ("select 오류: ", "Select error: "),
    ("PPTP 프로세스 종료 코드: ", "PPTP process exit code: "),
    ("PPTP 프로세스 종료", "PPTP process exited"),
    ("PPTP 연결 종료", "PPTP connection ended")
]

func translated(_ text: String, korean: Bool) -> String {
    guard !korean else { return text }
    if let exact = englishText[text] { return exact }
    var result = text
    for (source, target) in englishFragments {
        result = result.replacingOccurrences(of: source, with: target)
    }
    result = result.replacingOccurrences(of: "([0-9]+)개", with: "$1", options: .regularExpression)
    return result
}

func tr(_ text: String) -> String {
    translated(text, korean: Locale.preferredLanguages.first?.lowercased().hasPrefix("ko") == true)
}
